Nivashini J




235229119

# Lab 1- Red Wine Quality Data Analytics Using NumPy Part 1

'\nWine quality dataset 11 input features and 1 output feature\n1 - fixed acidity\n2 - volatile acidity\n3 - citric acid\n4 - residual sugar\n5 - chlorides\n6 - free sulfur dioxide\n7 - total sulfur dioxide\n8 - density\n9 - pH\n10 - sulphates\n11 - alcohol\nOutput variable (based on sensory data):\n12 - quality (score between 0 and 10)'

### import modules for numpy.

In [1]:
import numpy as np

In [2]:
wines=np.genfromtxt('winequality-red.csv',delimiter=";",skip_header=1)

### What is its size?

In [3]:
wines.shape

(1599,)

### How many wine data rows here?

In [4]:
wines.shape[0]

1599

### How many wine data columns here?

In [5]:
wines.shape[1]

IndexError: tuple index out of range

### How many dimensions?

In [6]:
wines.ndim

1

### What is the type of wines?

In [9]:
type(wines)

numpy.ndarray

### What is the data type of wines data?

In [10]:
wines.dtype

dtype('float64')

### Show top 5 rows

In [11]:
wines[:5][:]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00]])

### What is the value at 3rd row, 4th column of wine data?

In [12]:
wines[2][3]

2.3

### Select first 3 items in 4th column

In [13]:
wines[:3,3]

array([1.9, 2.6, 2.3])

### Show 1st column

In [14]:
wines[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

### Show 2nd row

In [15]:
wines[1,:]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

### Select items from rows 1 to 3 and 5th column

In [16]:
wines[1:4,4]

array([0.098, 0.092, 0.075])

### Select items from rows 1 to 3 and 5th column

In [17]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

### Change 1st value in wines to 100

In [18]:
#show actual value

In [19]:
wines[0,0]

7.4

In [20]:
#update

In [21]:
wines[0,0]=100

In [22]:
#show updated value

In [23]:
wines[0,0]

100.0

In [24]:
#change it back to 7.4 and print

In [25]:
wines[0,0]=7.4

### 1- Dimensional Numpy Arrays

### Select 4th row all column values

In [26]:
a=wines[3,:]

### display its value

In [27]:
a

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

### show 2nd value

In [28]:
a[1]

0.28

### convert wine data to integer values and show it

In [29]:
wines.astype(int)

array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

### Vectorization Operations

### Increase wine quality score (output variable) by 10

In [30]:
wines[:, 11]


array([5., 5., 5., ..., 6., 5., 6.])

### increase by 10

In [31]:
wines[:,11]+=10

### Display update score

In [32]:
wines[:,11]

array([15., 15., 15., ..., 16., 15., 16.])

### Multiply alcohol of all wine data by 3 times

In [33]:
wines[:,10]*=3

### show updated alcohol column

In [34]:
wines[:,10]

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

### Add quality column by itself

In [35]:
wines[:,11]+wines[:,11]

array([30., 30., 30., ..., 32., 30., 32.])

### Multiply alcohol and wine quality columns.It will perform element wise multiplication

In [36]:
wines[:,11]*wines[:,10]

array([423., 441., 441., ..., 528., 459., 528.])

### Broadcasting

### Add every row of wines data with a random array of values

In [37]:
rand_array=np.random.rand(12)

### show rand_array

In [38]:
rand_array

array([0.86996964, 0.34322564, 0.62152288, 0.70836004, 0.91059921,
       0.60984851, 0.98396151, 0.89562856, 0.36918268, 0.6124475 ,
       0.06772004, 0.19442878])

### add wines and rand_array

In [39]:
wines+rand_array

array([[ 8.26996964,  1.04322564,  0.62152288, ...,  1.1724475 ,
        28.26772004, 15.19442878],
       [ 8.66996964,  1.22322564,  0.62152288, ...,  1.2924475 ,
        29.46772004, 15.19442878],
       [ 8.66996964,  1.10322564,  0.66152288, ...,  1.2624475 ,
        29.46772004, 15.19442878],
       ...,
       [ 7.16996964,  0.85322564,  0.75152288, ...,  1.3624475 ,
        33.06772004, 16.19442878],
       [ 6.76996964,  0.98822564,  0.74152288, ...,  1.3224475 ,
        30.66772004, 15.19442878],
       [ 6.86996964,  0.65322564,  1.09152288, ...,  1.2724475 ,
        33.06772004, 16.19442878]])