Nivshini J


235229119

In [1]:
import numpy as np 
wines=np.genfromtxt("redwinequality.csv",delimiter=",",skip_header=1)

FileNotFoundError: redwinequality.csv not found.

In [ ]:
wines[:,3].sum()   # sum of all residual sugar values

4059.55

In [8]:
sum(wines[:])  # sums fo every feature value there 12 feature

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

In [9]:
#np.sum(wines)


In [10]:
a=wines.sum(axis=1)  #  add all columns  in each rows
\
a

array([ 74.5438 , 123.0548 ,  99.699  , ..., 100.48174, 105.21547,
        92.49249])

In [11]:
a=wines.sum(axis=0)   # add all rows in each columns
a

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

In [13]:
a.shape


(12,)

In [14]:
wines.shape

(1599, 12)

In [15]:
b=wines[:,3]
b=b.astype(int)
b

array([1, 2, 2, ..., 2, 2, 3])

In [16]:
b.max()

15

In [17]:
b.min()

0

In [18]:
b.mean()

2.0950594121325827

In [19]:
np.percentile(b,25)   # 25 percentile residual sugar value

1.0

In [20]:
wines.mean(axis=0)   # average of feature values

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

comparisons


In [21]:
wines[:11]>5   # show all wines with quality >5

array([[ True, False, False, False, False,  True,  True, False, False,
        False,  True, False],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True, False],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True, False],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True,  True],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True, False],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True, False],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True, False],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True,  True],
       [ True, False, False, False, False,  True,  True, False, False,
        False,  True,  True],
       [ True, False, False,  True, False,  True,  True, False, False,
        False,  True

In [ ]:
d=wines[:,11]>7 # show all wines with quality>7

In [22]:
d=wines[:,11]>7   # any wines value in true for the condition quality >7
True in d

True

show first 3 rows where wine quality greater than 7 , call it high quality

In [26]:
high_quality=wines[:,11]>7


False

show only top 3 rows and all columns of high quality wine data

In [28]:
high_quality_first_3_rows=wines[high_quality][0:3]
high_quality_first_3_rows

TypeError: 'numpy.bool_' object does not support item assignment

show wines with a lot of alchol>10 and high wine quality>10


In [ ]:
alcohol_wines=(wines[:,10]>10)&(wines[:,11]>7)
alcohol_wines

show only alcohol and wine quality columns

In [ ]:
wines[alcohol_wines,10:]

combining Numpy arrays


open white wine dataset

In [ ]:
white_wine=np.genfromtxt("winequality-white.csv",delimiter=";",skip_header=1)






In [ ]:
white_wine.size

In [ ]:
white_wine.shape


what is the size of all_wines

In [ ]:
all_wines=np.vstack((wines,white_wine),axis=0)
all_wines.shape

In [ ]:
data2=np.concatenate((wines,white_wine),axis=0)


In [ ]:
data2.shape

find transpose and print size 

In [ ]:
ce=np.transpose(wines)

In [ ]:
ce.shape

convert wines data in 1dimension array

In [ ]:
wines.ravel().size

In [ ]:
wines.ravel()

                         reshape second row of wines into 2 dimension array with 2 rows and 6 columns

In [ ]:
wines[1,:].reshape(2,6)


sort alcohol columns ascending order

In [ ]:
np.sort(wines[:,10])

In [ ]:
sort alcohol columns descending order

In [ ]:
np.sort(wines[:,10])[::-1]

In [ ]:
what